# Generated by Django 4.1.7 on 2023-02-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '4')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_book.showbook')),
            ],
        ),
    ]
